"""BibTeX formatting utilities."""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from arxiv2md_beta.citations.models import CitationEntry


def _escape_bibtex(text: str | None) -> str:
    """Escape special characters for BibTeX."""
    if not text:
        return ""
    # Escape special characters
    text = text.replace("\\", "\\textbackslash{}")
    text = text.replace("{", "\\{")
    text = text.replace("}", "\\}")
    text = text.replace("&", "\\&")
    text = text.replace("%", "\\%")
    text = text.replace("$", "\\$")
    text = text.replace("#", "\\#")
    text = text.replace("_", "\\_")
    text = text.replace("^", "\\^{}")
    text = text.replace("~", "\\textasciitilde{}")
    return text


def _format_authors(authors: list[str]) -> str:
    """Format author list for BibTeX."""
    if not authors:
        return ""
    # BibTeX uses "and" separator
    formatted = []
    for author in authors:
        # Try to convert "First Last" to "Last, First"
        parts = author.strip().split()
        if len(parts) >= 2:
            # Assume last part is surname
            surname = parts[-1]
            given = " ".join(parts[:-1])
            formatted.append(f"{surname}, {given}")
        else:
            formatted.append(author)
    return " and ".join(formatted)


def format_bibtex_entry(entry: "CitationEntry") -> str:
    """Format a CitationEntry as BibTeX.

    Parameters
    ----------
    entry : CitationEntry
        The citation entry to format

    Returns
    -------
    str
        BibTeX formatted entry
    """
    lines = [f"@{entry.entry_type}{{{entry.key},"]

    # Required/optional fields based on entry type
    fields = []

    if entry.title:
        fields.append(("title", _escape_bibtex(entry.title)))

    if entry.authors:
        fields.append(("author", _format_authors(entry.authors)))

    if entry.year:
        fields.append(("year", entry.year))

    if entry.journal and entry.entry_type == "article":
        fields.append(("journal", _escape_bibtex(entry.journal)))

    if entry.booktitle and entry.entry_type in ("inproceedings", "incollection"):
        fields.append(("booktitle", _escape_bibtex(entry.booktitle)))

    if entry.volume:
        fields.append(("volume", entry.volume))

    if entry.issue:
        fields.append(("number", entry.issue))

    if entry.pages:
        fields.append(("pages", entry.pages))

    if entry.doi:
        fields.append(("doi", entry.doi))

    if entry.url:
        fields.append(("url", entry.url))

    if entry.publisher:
        fields.append(("publisher", _escape_bibtex(entry.publisher)))

    if entry.abstract:
        # Multi-line abstract needs special handling
        escaped = _escape_bibtex(entry.abstract)
        fields.append(("abstract", escaped))

    if entry.note:
        fields.append(("note", _escape_bibtex(entry.note)))

    # Format fields with proper indentation
    for key, value in fields:
        lines.append(f"  {key} = {{{value}}},")

    lines.append("}")

    return "\n".join(lines)


def format_bibtex_database(entries: list["CitationEntry"]) -> str:
    """Format multiple entries as a BibTeX database.

    Parameters
    ----------
    entries : list[CitationEntry]
        List of citation entries

    Returns
    -------
    str
        Complete BibTeX database
    """
    if not entries:
        return ""

    parts = [
        "% Generated by arxiv2md-beta",
        "",
    ]

    for entry in entries:
        parts.append(entry.to_bibtex())
        parts.append("")

    return "\n".join(parts)


def generate_citation_key(
    authors: list[str],
    year: str | None,
    title: str | None,
    index: int = 0,
) -> str:
    """Generate a unique citation key.

    Parameters
    ----------
    authors : list[str]
        List of author names
    year : str | None
        Publication year
    title : str | None
        Paper title
    index : int
        Index for disambiguation

    Returns
    -------
    str
        Generated citation key
    """
    parts = []

    # Add first author's last name
    if authors:
        first_author = authors[0]
        # Extract surname (assume "First Last" or "Last, First" format)
        if "," in first_author:
            surname = first_author.split(",")[0].strip()
        else:
            surname = first_author.split()[-1]
        # Remove non-alphanumeric
        surname = re.sub(r"[^\w]", "", surname)
        parts.append(surname)

    # Add year
    if year:
        parts.append(year)

    # Add first word of title if needed for uniqueness
    if title and not authors:
        first_word = title.split()[0] if title.split() else "ref"
        first_word = re.sub(r"[^\w]", "", first_word)
        parts.append(first_word)

    key = "".join(parts) if parts else f"ref{index}"

    # Add index if provided for disambiguation
    if index > 0:
        key = f"{key}{index}"

    return key.lower()
