"""BibTeX formatting utilities."""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from arxiv2md_beta.citations.models import CitationEntry


def _escape_bibtex(text: str | None) -> str:
    """Escape special characters for BibTeX."""
    if not text:
        return ""
    # Escape special characters
    text = text.replace("\\", "\\textbackslash{}")
    text = text.replace("{", "\\{")
    text = text.replace("}", "\\}")
    text = text.replace("&", "\\&")
    text = text.replace("%", "\\%")
    text = text.replace("$", "\\$")
    text = text.replace("#", "\\#")
    text = text.replace("_", "\\_")
    text = text.replace("^", "\\^{}")
    text = text.replace("~", "\\textasciitilde{}")
    return text


def _format_authors(authors: list[str]) -> str:
    """Format author list for BibTeX."""
    if not authors:
        return ""
    # BibTeX uses "and" separator
    formatted = []
    for author in authors:
        # Try to convert "First Last" to "Last, First"
        parts = author.strip().split()
        if len(parts) >= 2:
            # Assume last part is surname
            surname = parts[-1]
            given = " ".join(parts[:-1])
            formatted.append(f"{surname}, {given}")
        else:
            formatted.append(author)
    return " and ".join(formatted)


def format_bibtex_entry(entry: CitationEntry) -> str:
    """Format a CitationEntry as BibTeX.

    Parameters
    ----------
    entry : CitationEntry
        The citation entry to format

    Returns:
    -------
    str
        BibTeX formatted entry
    """
    lines = [f"@{entry.entry_type}{{{entry.key},"]

    # Required/optional fields based on entry type
    fields = []

    if entry.title:
        fields.append(("title", _escape_bibtex(entry.title)))

    if entry.authors:
        fields.append(("author", _format_authors(entry.authors)))

    if entry.year:
        fields.append(("year", entry.year))

    if entry.journal and entry.entry_type == "article":
        fields.append(("journal", _escape_bibtex(entry.journal)))

    if entry.booktitle and entry.entry_type in ("inproceedings", "incollection"):
        fields.append(("booktitle", _escape_bibtex(entry.booktitle)))

    if entry.volume:
        fields.append(("volume", entry.volume))

    if entry.issue:
        fields.append(("number", entry.issue))

    if entry.pages:
        fields.append(("pages", entry.pages))

    if entry.doi:
        fields.append(("doi", entry.doi))

    if entry.url:
        fields.append(("url", entry.url))

    if entry.publisher:
        fields.append(("publisher", _escape_bibtex(entry.publisher)))

    if entry.abstract:
        # Multi-line abstract needs special handling
        escaped = _escape_bibtex(entry.abstract)
        fields.append(("abstract", escaped))

    if entry.note:
        fields.append(("note", _escape_bibtex(entry.note)))

    # Format fields with proper indentation
    for key, value in fields:
        lines.append(f"  {key} = {{{value}}},")

    lines.append("}")

    return "\n".join(lines)


def format_bibtex_database(entries: list[CitationEntry]) -> str:
    """Format multiple entries as a BibTeX database.

    Parameters
    ----------
    entries : list[CitationEntry]
        List of citation entries

    Returns:
    -------
    str
        Complete BibTeX database
    """
    if not entries:
        return ""

    parts = [
        "% Generated by arxiv2md-beta",
        "",
    ]

    # BibTeX rejects duplicate keys; the same DOI cited twice resolved to one
    # shared entry object and used to be emitted twice (audit5 G4-4). Dedupe
    # by DOI (case-insensitive — DOI matching is case-insensitive), falling
    # back to the key for entries without one.
    seen: set[str] = set()
    for entry in entries:
        identity = entry.doi.lower() if entry.doi else f"key:{entry.key}"
        if identity in seen:
            continue
        seen.add(identity)
        parts.append(entry.to_bibtex())
        parts.append("")

    return "\n".join(parts)


def extract_citation_surname(author: str) -> str:
    """Extract the surname from ``"First Last"`` or ``"Last, First"``.

    Shared by :func:`generate_citation_key` and the Atom-feed BibTeX
    generator in ``network/arxiv_api.py`` so the two cannot drift. Returns
    ``""`` (never raises) when nothing usable is present.
    """
    if "," in author:
        return author.split(",")[0].strip()
    parts = author.split()
    return parts[-1] if parts else ""


def clean_citation_key_token(token: str) -> str:
    r"""Unicode-aware BibTeX key token cleanup (``re.sub(r"[^\w]", "", …)``).

    Deliberately ``[^\w]``, not the old ``[^a-zA-Z]``: the ASCII-only
    pattern stripped "Müller" to ``""`` and collapsed keys to
    ``{year}{yymm}``, which collides across papers (audit5 G4-5), and it
    also broke CJK names (audit5 R-14).
    """
    return re.sub(r"[^\w]", "", token)


def generate_citation_key(
    authors: list[str],
    year: str | None,
    title: str | None,
    index: int = 0,
) -> str:
    """Generate a unique citation key.

    Parameters
    ----------
    authors : list[str]
        List of author names
    year : str | None
        Publication year
    title : str | None
        Paper title
    index : int
        Index for disambiguation

    Returns:
    -------
    str
        Generated citation key
    """
    parts = []

    # Add first author's last name
    if authors:
        surname = clean_citation_key_token(extract_citation_surname(authors[0]))
        parts.append(surname)

    # Add year
    if year:
        parts.append(year)

    # Add first word of title if needed for uniqueness
    if title and not authors:
        first_word = title.split()[0] if title.split() else "ref"
        first_word = clean_citation_key_token(first_word)
        parts.append(first_word)

    key = "".join(parts) if parts else f"ref{index}"

    # Add index if provided for disambiguation
    if index > 0:
        key = f"{key}{index}"

    return key.lower()
