"""Tests for citation resolution and BibTeX export."""

from __future__ import annotations

import pytest

from arxiv2md_beta.citations import (
    CitationEntry,
    CitationResolver,
    ParsedCitation,
    extract_identifiers,
    format_bibtex_database,
    format_bibtex_entry,
    parse_citations_from_html,
    parse_citations_from_text,
)


class TestCitationEntry:
    """Tests for CitationEntry dataclass."""

    def test_citation_entry_creation(self):
        """Test creating a citation entry."""
        entry = CitationEntry(
            key="smith2024",
            title="Test Paper Title",
            authors=["John Smith", "Jane Doe"],
            year="2024",
            journal="Journal of Testing",
            volume="42",
            issue="3",
            pages="100-110",
            doi="10.1234/test.2024",
        )
        assert entry.key == "smith2024"
        assert entry.title == "Test Paper Title"
        assert len(entry.authors) == 2

    def test_citation_entry_to_bibtex(self):
        """Test converting entry to BibTeX."""
        entry = CitationEntry(
            key="smith2024",
            title="Test Paper Title",
            authors=["John Smith", "Jane Doe"],
            year="2024",
            journal="Journal of Testing",
            doi="10.1234/test.2024",
        )
        bibtex = entry.to_bibtex()
        assert "@article{smith2024," in bibtex
        assert "title = {Test Paper Title}," in bibtex
        assert "author = {Smith, John and Doe, Jane}," in bibtex
        assert "year = {2024}," in bibtex
        assert "journal = {Journal of Testing}," in bibtex
        assert "doi = {10.1234/test.2024}," in bibtex


class TestBibtexFormatter:
    """Tests for BibTeX formatting."""

    def test_format_bibtex_article(self):
        """Test formatting article entry."""
        entry = CitationEntry(
            key="test2024",
            title="A Test Article",
            authors=["Test Author"],
            year="2024",
            journal="Test Journal",
            volume="1",
            pages="1-10",
        )
        bibtex = format_bibtex_entry(entry)
        assert "@article{test2024," in bibtex
        assert "journal = {Test Journal}," in bibtex

    def test_format_bibtex_inproceedings(self):
        """Test formatting inproceedings entry."""
        entry = CitationEntry(
            key="conf2024",
            title="A Conference Paper",
            authors=["Author One"],
            year="2024",
            booktitle="Proceedings of the Test Conference",
            entry_type="inproceedings",
        )
        bibtex = format_bibtex_entry(entry)
        assert "@inproceedings{conf2024," in bibtex
        assert "booktitle = {Proceedings of the Test Conference}," in bibtex

    def test_format_bibtex_database(self):
        """Test formatting multiple entries."""
        entries = [
            CitationEntry(key="ref1", title="First", authors=["A"], year="2024"),
            CitationEntry(key="ref2", title="Second", authors=["B"], year="2023"),
        ]
        bibtex = format_bibtex_database(entries)
        assert "@article{ref1," in bibtex
        assert "@article{ref2," in bibtex
        assert "Generated by arxiv2md-beta" in bibtex

    def test_escape_special_chars(self):
        """Test escaping special BibTeX characters."""
        entry = CitationEntry(
            key="test",
            title="Title with \\ & % $ # _ ^ ~",
            authors=["Author"],
            year="2024",
        )
        bibtex = format_bibtex_entry(entry)
        assert "\\textbackslash" in bibtex
        assert "\\&" in bibtex
        assert "\\%" in bibtex
        assert "\\$" in bibtex


class TestIdentifierExtraction:
    """Tests for identifier extraction from text."""

    def test_extract_doi(self):
        """Extract DOI from text."""
        text = "See paper doi: 10.1234/example for details."
        ids = extract_identifiers(text)
        assert ids["doi"] == "10.1234/example"

    def test_extract_arxiv_id(self):
        """Extract arXiv ID from text."""
        text = "Available at arXiv:2305.12345"
        ids = extract_identifiers(text)
        assert ids["arxiv_id"] == "2305.12345"

    def test_extract_pmid(self):
        """Extract PubMed ID from text."""
        text = "PMID: 12345678"
        ids = extract_identifiers(text)
        assert ids["pmid"] == "12345678"

    def test_extract_url(self):
        """Extract URL from text."""
        text = "Available at https://example.com/paper"
        ids = extract_identifiers(text)
        assert ids["url"] == "https://example.com/paper"

    def test_extract_multiple(self):
        """Extract multiple identifiers."""
        text = "DOI: 10.1234/test arXiv:2305.12345"
        ids = extract_identifiers(text)
        assert "doi" in ids
        assert "arxiv_id" in ids


class TestCitationParsing:
    """Tests for citation parsing from HTML/text."""

    def test_parse_citations_from_html_bibliography(self):
        """Parse citations from HTML bibliography section."""
        html = """
        <section class="ltx_bibliography">
            <h2>References</h2>
            <ul>
                <li id="bib.bib1">Smith, J. (2024). Test paper. Journal, 1(1), 1-10.</li>
                <li id="bib.bib2">DOI: 10.1234/example</li>
            </ul>
        </section>
        """
        citations = parse_citations_from_html(html)
        assert len(citations) == 2
        assert citations[0].key == "bib1"
        assert "Smith" in citations[0].text
        assert citations[1].identifiers.get("doi") == "10.1234/example"

    def test_parse_citations_from_html_div_bibliography(self):
        """audit5 R-13: the tag must not matter, only the class.

        ar5iv sometimes emits the bibliography as a div/ul rather than a
        section.
        """
        html = """
        <div class="ltx_bibliography">
            <ul>
                <li id="bib.bib1">Smith, J. (2024). Test paper. Journal, 1(1), 1-10.</li>
                <li id="bib.bib2">DOI: 10.1234/example</li>
            </ul>
        </div>
        """
        citations = parse_citations_from_html(html)
        assert len(citations) == 2
        assert citations[0].key == "bib1"
        assert citations[1].identifiers.get("doi") == "10.1234/example"

    def test_parse_citations_from_text(self):
        """Parse citations from plain text."""
        text = """
[1] Smith, J. (2024). First paper. Journal A.
[2] Doe, J. (2023). Second paper. Journal B. DOI: 10.1234/test
        """
        citations = parse_citations_from_text(text)
        assert len(citations) == 2
        assert citations[0].text.startswith("[1]")
        assert citations[1].identifiers.get("doi") == "10.1234/test"


class TestCitationResolver:
    """Tests for CitationResolver."""

    @pytest.mark.asyncio
    async def test_resolve_citation_with_doi(self):
        """Test resolving citation with DOI."""
        ParsedCitation(
            key="test",
            text="Test citation",
            identifiers={"doi": "10.1234/example"},
        )

        resolver = CitationResolver()
        # This would need mocking of fetch_crossref_metadata
        # For now, just test the structure
        assert resolver is not None

    def test_generate_citation_key(self):
        """Test citation key generation."""
        from arxiv2md_beta.citations.formatter import generate_citation_key

        key = generate_citation_key(
            authors=["John Smith", "Jane Doe"],
            year="2024",
            title="Test Paper",
        )
        assert "smith" in key.lower()
        assert "2024" in key


class TestSingleFlightCoalescing:
    """Duplicate identifiers in flight resolve once (one HTTP call)."""

    def test_coalesced_doi_resolves_once(self) -> None:
        import asyncio
        from unittest.mock import patch

        from arxiv2md_beta.citations.models import CitationEntry, ParsedCitation
        from arxiv2md_beta.citations.resolver import CitationResolver

        async def run() -> tuple[int, list]:
            resolver = CitationResolver()
            calls = {"n": 0}

            async def fake_resolve(parsed: ParsedCitation, index: int):
                calls["n"] += 1
                await asyncio.sleep(0.01)
                return CitationEntry(key=f"k{index}", title="T", authors=[], year=2024)

            parsed1 = ParsedCitation(key="a", text="a", identifiers={"doi": "10.1000/x"})
            parsed2 = ParsedCitation(key="b", text="b", identifiers={"doi": "10.1000/x"})
            with patch.object(resolver, "_resolve_by_doi", side_effect=fake_resolve):
                results = await asyncio.gather(
                    resolver.resolve_citation(parsed1, 0),
                    resolver.resolve_citation(parsed2, 1),
                )
            return calls["n"], results

        n, results = asyncio.run(run())
        assert n == 1  # second caller joined the in-flight task
        assert all(r is not None for r in results)


class TestYearExtractionFromText:
    """Regression: the fallback year extractor must keep the full year."""

    def test_year_is_full_match_not_century(self):
        # group(1) of r"\b(19|20)\d{2}\b" is "19"/"20" — every fallback
        # entry used to get year "20" instead of e.g. "2015".
        resolver = CitationResolver()
        parsed = ParsedCitation(key="nature2015", text="A study. Nature 2015.")
        entry = resolver._create_entry_from_text(parsed, index=7)
        assert entry.year == "2015"

    def test_year_19xx(self):
        resolver = CitationResolver()
        parsed = ParsedCitation(key="old", text="Proc. of 1998 workshop")
        entry = resolver._create_entry_from_text(parsed, index=1)
        assert entry.year == "1998"

    def test_no_year(self):
        resolver = CitationResolver()
        parsed = ParsedCitation(key="none", text="No date in here")
        entry = resolver._create_entry_from_text(parsed, index=2)
        assert entry.year is None


def test_generate_citation_null_author_name() -> None:
    """Null Atom author names fall back to Unknown, never literal None."""
    from arxiv2md_beta.network.arxiv_api import _generate_citation

    cite = _generate_citation([{"name": None}, {"name": "Real Author"}], "2025", "A Title", "2501.00000")
    assert "None" not in cite
    assert "Unknown" in cite


class TestCrossrefTitleExtraction:
    """audit5 C5: Crossref's article title, not the journal, is the title."""

    def test_parse_extracts_article_title(self):
        from arxiv2md_beta.network.crossref_api import _parse_crossref_response

        metadata = _parse_crossref_response(
            {"message": {"title": ["Real Article Title"], "container-title": ["Nature"]}}
        )
        assert metadata["title"] == "Real Article Title"
        assert metadata["container_title"] == "Nature"

    def test_resolve_by_doi_uses_article_title(self):
        import asyncio
        from unittest.mock import patch

        from arxiv2md_beta.citations.models import ParsedCitation
        from arxiv2md_beta.citations.resolver import CitationResolver

        async def run():
            async def fake_fetch(doi, **kwargs):
                return {
                    "title": "Real Article Title",
                    "container_title": "Nature",
                    "published_print_year": "2015",
                    "crossref_authors": [{"name": "Ada Lovelace"}],
                }

            resolver = CitationResolver()
            parsed = ParsedCitation(key="x", text="x", identifiers={"doi": "10.1234/real"})
            with patch("arxiv2md_beta.citations.resolver.fetch_crossref_metadata", side_effect=fake_fetch):
                return await resolver.resolve_citation(parsed, 0)

        entry = asyncio.run(run())
        assert entry.title == "Real Article Title"
        assert entry.journal == "Nature"

    def test_resolve_by_doi_uses_structured_family_given(self):
        """audit5 R-14: Crossref given/family must reach the entry directly.

        The display name "Jun Liu" fed the surname heuristic, which took the
        last whitespace token and produced the key "liu…" for family=Liu —
        wrong for "van der Berg S.", "Y. Chen Jr.", and CJK names alike.
        """
        import asyncio
        from unittest.mock import patch

        from arxiv2md_beta.citations.models import ParsedCitation
        from arxiv2md_beta.citations.resolver import CitationResolver
        from arxiv2md_beta.network.crossref_api import _parse_crossref_response

        async def run():
            metadata = _parse_crossref_response(
                {
                    "message": {
                        "title": ["Structured Authors"],
                        "container-title": "Journal of Names",
                        "published-print": {"date-parts": [[2019, 5, 1]]},
                        "author": [
                            {"given": "Jun", "family": "Liu"},
                            {"given": "Sanne", "family": "van der Berg"},
                            {"given": "Y.", "family": "Chen", "suffix": "Jr."},
                        ],
                    }
                }
            )

            async def fake_fetch(doi, **kwargs):
                return metadata

            resolver = CitationResolver()
            parsed = ParsedCitation(key="x", text="x", identifiers={"doi": "10.1234/names"})
            with patch("arxiv2md_beta.citations.resolver.fetch_crossref_metadata", side_effect=fake_fetch):
                return await resolver.resolve_citation(parsed, 0)

        entry = asyncio.run(run())
        assert entry.authors == ["Liu, Jun", "van der Berg, Sanne", "Chen, Y. Jr."]
        assert entry.key.startswith("liu2019")

    def test_title_falls_back_to_container_when_absent(self):
        import asyncio
        from unittest.mock import patch

        from arxiv2md_beta.citations.models import ParsedCitation
        from arxiv2md_beta.citations.resolver import CitationResolver

        async def run():
            async def fake_fetch(doi, **kwargs):
                return {"container_title": "Legacy Journal", "published_print_year": "2010"}

            resolver = CitationResolver()
            parsed = ParsedCitation(key="x", text="x", identifiers={"doi": "10.1234/old"})
            with patch("arxiv2md_beta.citations.resolver.fetch_crossref_metadata", side_effect=fake_fetch):
                return await resolver.resolve_citation(parsed, 0)

        entry = asyncio.run(run())
        assert entry.title == "Legacy Journal"


class TestBibtexDatabaseDedup:
    """audit5 G4-4: repeated citations must not emit duplicate BibTeX keys."""

    def test_same_doi_emitted_once(self):
        from arxiv2md_beta.citations.formatter import format_bibtex_database
        from arxiv2md_beta.citations.models import CitationEntry

        entries = [
            CitationEntry(key="smith2015", title="T", doi="10.1234/Dup"),
            CitationEntry(key="smith20157", title="T", doi="10.1234/dup"),
        ]
        out = format_bibtex_database(entries)
        assert out.count("@") == 1

    def test_same_key_emitted_once(self):
        from arxiv2md_beta.citations.formatter import format_bibtex_database
        from arxiv2md_beta.citations.models import CitationEntry

        entries = [
            CitationEntry(key="dup", title="T"),
            CitationEntry(key="dup", title="T"),
        ]
        out = format_bibtex_database(entries)
        assert out.count("@") == 1

    def test_distinct_entries_all_kept(self):
        from arxiv2md_beta.citations.formatter import format_bibtex_database
        from arxiv2md_beta.citations.models import CitationEntry

        entries = [
            CitationEntry(key="a2020", title="A", doi="10.1/a"),
            CitationEntry(key="b2021", title="B", doi="10.1/b"),
        ]
        out = format_bibtex_database(entries)
        assert out.count("@") == 2


class TestDoiHygiene:
    """audit5 R12: DOI extraction/caching edge cases."""

    def test_trailing_comma_and_paren_stripped(self):
        ids = extract_identifiers("as shown in (Nature, 10.1234/x.y, 2015).")
        assert ids["doi"] == "10.1234/x.y"

    def test_balanced_paren_doi_kept(self):
        ids = extract_identifiers("see 10.1234/(SICI)1097-4628 paper")
        assert ids["doi"] == "10.1234/(SICI)1097-4628"

    def test_http_doi_url_not_captured_as_url(self):
        ids = extract_identifiers("available at http://doi.org/10.1234/abc")
        assert "url" not in ids
        assert ids["doi"].endswith("10.1234/abc")

    def test_doi_cache_is_case_insensitive(self):
        import asyncio
        from unittest.mock import patch

        from arxiv2md_beta.citations.models import CitationEntry, ParsedCitation
        from arxiv2md_beta.citations.resolver import CitationResolver

        async def run():
            calls = {"n": 0}

            async def fake_resolve(parsed: ParsedCitation, index: int):
                calls["n"] += 1
                return CitationEntry(key="k", title="T")

            resolver = CitationResolver()
            p1 = ParsedCitation(key="a", text="a", identifiers={"doi": "10.1234/ABC"})
            p2 = ParsedCitation(key="b", text="b", identifiers={"doi": "10.1234/abc"})
            with patch.object(resolver, "_resolve_by_doi", side_effect=fake_resolve):
                e1 = await resolver.resolve_citation(p1, 0)
                e2 = await resolver.resolve_citation(p2, 1)
            return calls["n"], e1, e2

        n, e1, e2 = asyncio.run(run())
        assert n == 1
        assert e1 is e2

    def test_failed_doi_not_refetched(self):
        import asyncio
        from unittest.mock import patch

        from arxiv2md_beta.citations.models import ParsedCitation
        from arxiv2md_beta.citations.resolver import CitationResolver

        async def run():
            calls = {"n": 0}

            async def fake_fetch(doi, **kwargs):
                calls["n"] += 1
                return None

            resolver = CitationResolver()
            parsed = ParsedCitation(key="a", text="Some text 2014", identifiers={"doi": "10.9999/void"})
            with patch("arxiv2md_beta.citations.resolver.fetch_crossref_metadata", side_effect=fake_fetch):
                await resolver.resolve_citation(parsed, 0)
                await resolver.resolve_citation(parsed, 1)
            return calls["n"]

        assert asyncio.run(run()) == 1
