"""Tests for citation resolution and BibTeX export."""

from __future__ import annotations

import pytest

from arxiv2md_beta.citations import (
    CitationEntry,
    CitationResolver,
    ParsedCitation,
    extract_identifiers,
    format_bibtex_entry,
    format_bibtex_database,
    parse_citations_from_html,
    parse_citations_from_text,
)


class TestCitationEntry:
    """Tests for CitationEntry dataclass."""

    def test_citation_entry_creation(self):
        """Test creating a citation entry."""
        entry = CitationEntry(
            key="smith2024",
            title="Test Paper Title",
            authors=["John Smith", "Jane Doe"],
            year="2024",
            journal="Journal of Testing",
            volume="42",
            issue="3",
            pages="100-110",
            doi="10.1234/test.2024",
        )
        assert entry.key == "smith2024"
        assert entry.title == "Test Paper Title"
        assert len(entry.authors) == 2

    def test_citation_entry_to_bibtex(self):
        """Test converting entry to BibTeX."""
        entry = CitationEntry(
            key="smith2024",
            title="Test Paper Title",
            authors=["John Smith", "Jane Doe"],
            year="2024",
            journal="Journal of Testing",
            doi="10.1234/test.2024",
        )
        bibtex = entry.to_bibtex()
        assert "@article{smith2024," in bibtex
        assert "title = {Test Paper Title}," in bibtex
        assert "author = {Smith, John and Doe, Jane}," in bibtex
        assert "year = {2024}," in bibtex
        assert "journal = {Journal of Testing}," in bibtex
        assert "doi = {10.1234/test.2024}," in bibtex


class TestBibtexFormatter:
    """Tests for BibTeX formatting."""

    def test_format_bibtex_article(self):
        """Test formatting article entry."""
        entry = CitationEntry(
            key="test2024",
            title="A Test Article",
            authors=["Test Author"],
            year="2024",
            journal="Test Journal",
            volume="1",
            pages="1-10",
        )
        bibtex = format_bibtex_entry(entry)
        assert "@article{test2024," in bibtex
        assert "journal = {Test Journal}," in bibtex

    def test_format_bibtex_inproceedings(self):
        """Test formatting inproceedings entry."""
        entry = CitationEntry(
            key="conf2024",
            title="A Conference Paper",
            authors=["Author One"],
            year="2024",
            booktitle="Proceedings of the Test Conference",
            entry_type="inproceedings",
        )
        bibtex = format_bibtex_entry(entry)
        assert "@inproceedings{conf2024," in bibtex
        assert "booktitle = {Proceedings of the Test Conference}," in bibtex

    def test_format_bibtex_database(self):
        """Test formatting multiple entries."""
        entries = [
            CitationEntry(key="ref1", title="First", authors=["A"], year="2024"),
            CitationEntry(key="ref2", title="Second", authors=["B"], year="2023"),
        ]
        bibtex = format_bibtex_database(entries)
        assert "@article{ref1," in bibtex
        assert "@article{ref2," in bibtex
        assert "Generated by arxiv2md-beta" in bibtex

    def test_escape_special_chars(self):
        """Test escaping special BibTeX characters."""
        entry = CitationEntry(
            key="test",
            title="Title with \\ & % $ # _ ^ ~",
            authors=["Author"],
            year="2024",
        )
        bibtex = format_bibtex_entry(entry)
        assert "\\textbackslash" in bibtex
        assert "\\&" in bibtex
        assert "\\%" in bibtex
        assert "\\$" in bibtex


class TestIdentifierExtraction:
    """Tests for identifier extraction from text."""

    def test_extract_doi(self):
        """Extract DOI from text."""
        text = "See paper doi: 10.1234/example for details."
        ids = extract_identifiers(text)
        assert ids["doi"] == "10.1234/example"

    def test_extract_arxiv_id(self):
        """Extract arXiv ID from text."""
        text = "Available at arXiv:2305.12345"
        ids = extract_identifiers(text)
        assert ids["arxiv_id"] == "2305.12345"

    def test_extract_pmid(self):
        """Extract PubMed ID from text."""
        text = "PMID: 12345678"
        ids = extract_identifiers(text)
        assert ids["pmid"] == "12345678"

    def test_extract_url(self):
        """Extract URL from text."""
        text = "Available at https://example.com/paper"
        ids = extract_identifiers(text)
        assert ids["url"] == "https://example.com/paper"

    def test_extract_multiple(self):
        """Extract multiple identifiers."""
        text = "DOI: 10.1234/test arXiv:2305.12345"
        ids = extract_identifiers(text)
        assert "doi" in ids
        assert "arxiv_id" in ids


class TestCitationParsing:
    """Tests for citation parsing from HTML/text."""

    def test_parse_citations_from_html_bibliography(self):
        """Parse citations from HTML bibliography section."""
        html = """
        <section class="ltx_bibliography">
            <h2>References</h2>
            <ul>
                <li id="bib.bib1">Smith, J. (2024). Test paper. Journal, 1(1), 1-10.</li>
                <li id="bib.bib2">DOI: 10.1234/example</li>
            </ul>
        </section>
        """
        citations = parse_citations_from_html(html)
        assert len(citations) == 2
        assert citations[0].key == "bib1"
        assert "Smith" in citations[0].text
        assert citations[1].identifiers.get("doi") == "10.1234/example"

    def test_parse_citations_from_text(self):
        """Parse citations from plain text."""
        text = """
[1] Smith, J. (2024). First paper. Journal A.
[2] Doe, J. (2023). Second paper. Journal B. DOI: 10.1234/test
        """
        citations = parse_citations_from_text(text)
        assert len(citations) == 2
        assert citations[0].text.startswith("[1]")
        assert citations[1].identifiers.get("doi") == "10.1234/test"


class TestCitationResolver:
    """Tests for CitationResolver."""

    @pytest.mark.asyncio
    async def test_resolve_citation_with_doi(self):
        """Test resolving citation with DOI."""
        parsed = ParsedCitation(
            key="test",
            text="Test citation",
            identifiers={"doi": "10.1234/example"},
        )

        resolver = CitationResolver()
        # This would need mocking of fetch_crossref_metadata
        # For now, just test the structure
        assert resolver is not None

    def test_generate_citation_key(self):
        """Test citation key generation."""
        from arxiv2md_beta.citations.formatter import generate_citation_key

        key = generate_citation_key(
            authors=["John Smith", "Jane Doe"],
            year="2024",
            title="Test Paper",
        )
        assert "smith" in key.lower()
        assert "2024" in key
