"""Regression tests for degraded LaTeXML output (2504.13837).

Style-violating TeX (e.g. ICML layout check failures) makes LaTeXML drop the
semantic ``ltx_title_document`` / ``ltx_authors`` / ``ltx_abstract`` markers:
title, authors, and abstract render as plain paragraphs before the first
section, and the ``<title>`` tag ends up holding the first figure caption.
"""

from __future__ import annotations

from arxiv2md_beta.html.parser import parse_arxiv_html

_DEGRADED_HTML = """
<html><head><title>Figure 1: (Left) The effect of current RLVR on LLM's reasoning
ability. Search trees are generated by repeated sampling.</title></head>
<body>
<article class="ltx_document">
<div class="ltx_para ltx_noindent"><p class="ltx_p">marginparsep has been altered.
topmargin has been altered.</p></div>
<div class="ltx_para ltx_noindent"><p class="ltx_p"><span
 class="ltx_text ltx_font_bold ltx_font_italic">The page layout violates the ICML style.</span></p></div>
<div class="ltx_para ltx_noindent"><p class="ltx_p">Please do not change the page layout, or include packages
 like geometry.</p></div>
<div class="ltx_para ltx_noindent"><p class="ltx_p"><span
 class="ltx_text ltx_font_bold">Does Reinforcement Learning Really Incentivize
 Reasoning Capacity in LLMs Beyond the Base Model?</span></p></div>
<div class="ltx_para ltx_noindent"><p class="ltx_p"><span
 class="ltx_text ltx_font_bold">Yang Yue<math alttext="{}^{1*}" display="inline"><semantics><annotation
 encoding="application/x-tex">{}^{1*}</annotation></semantics></math></span><span
 class="ltx_text ltx_font_bold">, Zhiqi Chen<math
 alttext="{}^{1}" display="inline"><semantics><annotation
 encoding="application/x-tex">{}^{1}</annotation></semantics></math></span>,
 <span class="ltx_text ltx_font_bold">Rui Lu</span></p></div>
<div class="ltx_para ltx_noindent"><p class="ltx_p">1 LeapLab, Tsinghua University
 2 Shanghai Jiao Tong University</p></div>
<div class="ltx_para ltx_noindent"><p class="ltx_p">Reinforcement Learning with
 Verifiable Rewards (RLVR) has recently demonstrated notable success in
 incentivizing the reasoning ability of large language models. However, current
 RLVR methods show limited capability in expanding the reasoning boundary.
 We conduct extensive experiments across various benchmarks.</p></div>
<figure class="ltx_figure"><figcaption class="ltx_caption">Figure 1: (Left) The
 effect of current RLVR.</figcaption></figure>
<section class="ltx_section"><h2 class="ltx_title ltx_title_section">1 Introduction</h2>
<p class="ltx_para">Body text.</p></section>
</article>
</body></html>
"""


def _parse() -> object:
    return parse_arxiv_html(_DEGRADED_HTML)


def test_degraded_title_is_not_caption() -> None:
    parsed = _parse()
    assert parsed.title == (
        "Does Reinforcement Learning Really Incentivize Reasoning Capacity in LLMs Beyond the Base Model?"
    )


def test_degraded_authors_extracted() -> None:
    parsed = _parse()
    assert [a.name for a in parsed.authors] == ["Yang Yue", "Zhiqi Chen", "Rui Lu"]


def test_degraded_abstract_extracted() -> None:
    parsed = _parse()
    assert parsed.abstract is not None
    assert parsed.abstract.startswith("Reinforcement Learning with Verifiable Rewards (RLVR) has recently demonstrated")
    assert "Figure 1" not in parsed.abstract


def test_degraded_abstract_html_available() -> None:
    parsed = _parse()
    assert parsed.abstract_html is not None
    assert "Verifiable Rewards (RLVR)" in parsed.abstract_html


def test_front_matter_captures_title_block_figure() -> None:
    parsed = _parse()
    assert parsed.front_matter_html is not None
    assert "ltx_figure" in parsed.front_matter_html


def test_title_tag_caption_never_leaks() -> None:
    # Even without a detectable degraded title, a figure caption in <title>
    # must not be returned as the paper title.
    html = """
    <html><head><title>Figure 1: Some long caption text that is not a title.</title></head>
    <body><article class="ltx_document">
    <section class="ltx_section"><h2 class="ltx_title ltx_title_section">1 Intro</h2>
    <p class="ltx_para">Body.</p></section></article></body></html>
    """
    parsed = parse_arxiv_html(html)
    assert parsed.title is None
